version: '2'

networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=uchat
    networks:
      - app-tier
  backend:
    image: 'uchat/backend:0.0.1'
    ports:
      - 4000:4000
    networks:
      - app-tier
  nginx:
    image: 'uchat/frontend:0.0.1'
    ports:
      - 80:8080
    networks:
      - app-tier
      
